### ISSUE TITLE
[BUG] Discussion board not available, but linked to

### ISSUE THREAD

**Issue by marckohlbrugge** [excid3/refer#23]
## Bug Report

**Describe the Bug:**

I wanted to make a feature request, but it links to a non-existing page.

**To Reproduce:**

1. https://github.com/excid3/refer/issues/new/choose
2. Click "Feature Request" -> "Open"
3. https://github.com/excid3/refer/discussions/new?category=ideas returns a 404

**Screenshots (if applicable):**

<img width="1245" alt="CleanShot 2024-09-19 at 12 06 45@2x" src="https://github.com/user-attachments/assets/9a6ad6fa-4850-4ec2-b870-0e56b03d06f9">

**Comment by excid3** [comment]
Forgot to turn on Discussions.
